### ISSUE TITLE
README.MD

### ISSUE THREAD

**Issue by jq488** [nyu-software-engineering/organizer#6]
- [x] Building and Testing
- [x] Additional Links
- [x] How to contribute

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-organizer - Every issue should be either a user story, a spike, or a task.  This issue is clearly a spike - it's something you have to do as a team that is not directly related to the user's experience using your app.

Every issue placed on the task board should have a team member(s) assigned to it, an estimate of work, acceptance criteria, and be given the proper milestone for the sprint.  Any user stories placed in the board should be broken up into tasks that are the piece of work necessary to be done in order to fulfill the user story.
